package co.edu.icesi.apexstore.db;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/** Crea el esquema transaccional y de auditoría de ApexStore. */
public final class EsquemaSql {
    private EsquemaSql() {
    }

    public static void crear(Connection conexion) throws SQLException {
        try (Statement st = conexion.createStatement()) {
            st.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS transacciones (
                      transaccion_id VARCHAR(64) PRIMARY KEY,
                      orden_id VARCHAR(64) NOT NULL UNIQUE,
                      codigo_medio_pago VARCHAR(32) NOT NULL,
                      monto_minor BIGINT NOT NULL CHECK (monto_minor > 0),
                      moneda VARCHAR(8) NOT NULL,
                      estado VARCHAR(16) NOT NULL,
                      referencia_externa VARCHAR(128),
                      motivo VARCHAR(256),
                      creada_ms BIGINT NOT NULL,
                      actualizada_ms BIGINT NOT NULL
                    )
                    """);
            st.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS auditoria (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      transaccion_id VARCHAR(64) NOT NULL,
                      evento VARCHAR(32) NOT NULL,
                      estado_anterior VARCHAR(16),
                      estado_nuevo VARCHAR(16),
                      detalle VARCHAR(512),
                      marca_tiempo_ms BIGINT NOT NULL
                    )
                    """);
        }
    }
}
