Ice.Default.Host=localhost
Ice.ThreadPool.Server.Size=8
Ice.ThreadPool.Server.SizeMax=64
Backend.Endpoints=tcp -h localhost -p 10000
Checkout.Orquestador.Proxy=OrquestadorPagos:tcp -h localhost -p 10000
Orquestador.Transacciones.Proxy=Transacciones:tcp -h localhost -p 10000
Receptor.Transacciones.Proxy=Transacciones:tcp -h localhost -p 10000
Receptor.Checkout.Proxy=ConfirmarCompra:tcp -h localhost -p 10000
Transacciones.Persistencia.Proxy=DbTransacciones:tcp -h localhost -p 10200
Orquestador.Medios=STRIPE,PSE,CRIPTO
Orquestador.Medio.STRIPE.Proxy=EstrategiaStripe:tcp -h localhost -p 10100
Orquestador.Medio.PSE.Proxy=EstrategiaPSE:tcp -h localhost -p 10100
Orquestador.Medio.CRIPTO.Proxy=EstrategiaCripto:tcp -h localhost -p 10100
Orquestador.AckTimeoutMs=200
Orquestador.Breaker.UmbralFallos=5
Orquestador.Breaker.AbiertoMs=3000
Orquestador.Bulkhead.MaxConcurrentes=64
Expiracion.TxPendienteMs=20000
Expiracion.PeriodoMs=2000
