Ice.Default.Host=localhost
Ice.ThreadPool.Server.Size=4
Ice.ThreadPool.Server.SizeMax=16
Db.Endpoints=tcp -h localhost -p 10200
Db.Url=jdbc:h2:file:./data/apexstore;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
Db.Usuario=sa
Db.Clave=
