Ice.Default.Host=localhost
Ice.ThreadPool.Server.Size=4
Ice.ThreadPool.Server.SizeMax=32
Pasarelas.Endpoints=tcp -h localhost -p 10100
Pasarela.Receptor.Proxy=ReceptorResultadosPagos:tcp -h localhost -p 10000
Pasarela.Callback.MaxIntentos=5
Pasarela.Callback.BackoffInicialMs=100
Pasarelas.Habilitadas=STRIPE,PSE,CRIPTO
Pasarela.STRIPE.Clase=co.edu.icesi.apexstore.pasarelas.StripeSimulada
Pasarela.STRIPE.Identidad=EstrategiaStripe
Pasarela.STRIPE.AckMs=0-0
Pasarela.STRIPE.CallbackMs=0-0
Pasarela.STRIPE.TasaRechazo=0.05
Pasarela.PSE.Clase=co.edu.icesi.apexstore.pasarelas.PseSimulada
Pasarela.PSE.Identidad=EstrategiaPSE
Pasarela.PSE.AckMs=0-0
Pasarela.PSE.CallbackMs=0-0
Pasarela.PSE.TasaRechazo=0.08
Pasarela.CRIPTO.Clase=co.edu.icesi.apexstore.pasarelas.CriptoSimulada
Pasarela.CRIPTO.Identidad=EstrategiaCripto
Pasarela.CRIPTO.AckMs=0-0
Pasarela.CRIPTO.CallbackMs=0-0
Pasarela.CRIPTO.TasaRechazo=0.03
